### PR TITLE
Preserve GLES versions for macOS GLSL fixes

### PR DESCRIPTION
**Pull request by garbear**
## Description

Replaces #36 and #37

* Removes explicit GLSL 110 and 120 directives so Kodi can select the active desktop context version while retaining the default ESSL 100 path on GLES.
* Promotes GLSL 130 sources to 150 for macOS core profiles. Kodi maps both versions to ESSL 300, preserving their GLES behavior.

This keeps the existing GLES behavior unchanged while fixing the macOS failures caused by legacy desktop GLSL versions being rejected in a core profile.

It also avoids the regressions in the previous approaches: #36 raised GLES2 shaders to ESSL 300, while #37 could drop GLSL 130 shaders to ESSL 100.

## How has this been tested?

Tested on macOS with Kodi's OpenGL RetroPlayer renderer:

* All **34/34** curated GLSL presets rendered successfully.
* Zero shader compile, link, creation, OpenGL, or `GL_INVALID_*` errors.
* All affected shared-source consumers were exercised.

GLES compatibility was also checked with Kodi-equivalent version mapping and ANGLE compile/link probes:

* GLSL 110/120 sources retain the ESSL 100 path.
* GLSL 130/150 sources retain the ESSL 300 path.
* **18/18** modified shaders preserve their previous GLES version mapping.
* Four strict ANGLE failures were reproduced unchanged from the baseline.

Hardware GLES testing is still in progress.

### CODE REVIEW

**Comment by KOPRajs** [comment]
@garbear What is the problem with the #36 ? I would still prefer that approach, if there are no issues with that.
Since the GLSL is not backward compatible, I would try to avoid removing specific version definitions from the shaders, if possible.

**Comment by garbear** [comment]
AI use:

The split isn't for OpenGL 2. It's for GLES2. Kodi still has current GLES2 targets (Android, iOS, Wayland, and GBM/tvOS fallbacks). Promoting the 110/120 sources to 150 changes Kodi's GLES mapping from ESSL 100 to 300, while promoting 130 to 150 leaves it at ESSL 300.

Evidence:

Kodi's GLES shader loader currently maps:

* GLSL 110/120 -> ESSL 100
* GLSL 130-320 -> ESSL 300

https://github.com/xbmc/xbmc/blob/master/xbmc/cores/RetroPlayer/shaders/gles/ShaderUtilsGLES.cpp

So #36 changes the 110/120 shaders from ESSL 100 to ESSL 300, while this PR keeps them on the same ESSL 100 path. For the GLSL 130 shaders, 130 -> 150 is safe because both map to ESSL 300.

There are still current Kodi configurations using GLES2:

* Android explicitly creates an ES2 context:
  https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/android/WinSystemAndroidGLESContext.cpp
* iOS explicitly uses `kEAGLRenderingAPIOpenGLES2`:
  https://github.com/xbmc/xbmc/blob/master/xbmc/platform/darwin/ios/IOSEAGLView.mm
* Wayland GLES explicitly creates an ES2 context:
  https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/wayland/WinSystemWaylandEGLContextGLES.cpp
* GBM tries GLES3 first but deliberately falls back to GLES2:
  https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/gbm/WinSystemGbmGLESContext.cpp

So the intent of the split is to keep the effective GLES version unchanged for every shader while fixing the macOS core-profile failures.

**Comment by KOPRajs** [comment]
Do we really use GLES2 context on many real devices? Do we use GLES2 on GLES3 capable devices as suggested? @garbear Do you run Kodi on the Shield in Android? Does it use GLES2?

I believe that we have already used some GLES3 specific features in the RetroPlayer renderer anyway.
Also, I thought that only limited number of old hardware not capable of GLES3 use Kodi with GLES2. On such weak hardware RetroPlayer experience is expected to be limited anyway and shaders almost not possible.

That is why I considered requiring GLES3 for those shaders as not practical limit.

**Comment by garbear** [comment]
AI use:

Yes, at least with current Kodi Android code we actually request GLES2 even on GLES3-capable devices.

`WinSystemAndroidGLESContext` selects `EGL_OPENGL_ES2_BIT` and creates the context with:

```cpp
EGL_CONTEXT_CLIENT_VERSION, 2
```

There isn't an ES3-first path like GBM has:

https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/android/WinSystemAndroidGLESContext.cpp

So unless I'm missing some Android-specific override elsewhere, Kodi on Shield is still using the ES2 context we request.

RetroPlayer also still has explicit GLES2 handling. For example `RenderBufferOpenGLES.cpp` has a GLES2 fallback for texture uploads, while the ES3-only texture swizzle is guarded by `GL_ES_VERSION_3_0`:

https://github.com/xbmc/xbmc/blob/master/xbmc/cores/RetroPlayer/buffers/RenderBufferOpenGLES.cpp

So I don't think GLES2 is just theoretical old-hardware compatibility at the moment. #36 would change these shaders from the ESSL 100 path they currently get on Android to ESSL 300, despite Kodi itself still requesting an ES2 context.

**Comment by garbear** [comment]
Tested on my Shield with this change, all shaders are working on Android GLES, except for:

* xBR-lv2
* xBR-lv2 (no blend)

Investigating this now.

**Comment by garbear** [comment]
Fixes those two: https://github.com/kodi-game/game.shader.presets/pull/39

Now all shaders work on both macOS and Shield

**Comment by KOPRajs** [comment]
@garbear Can you please verify on your Shield with Android what GL version does it show in System information? I still don't want to believe we use only GLES2 on all Android even if they can use GLES3.

**Comment by garbear** [comment]
My Shield says "OpenGL ES 3.2 NVIDIA 495.00". Did the AI hallucinate?

**Comment by KOPRajs** [comment]
> My Shield says "OpenGL ES 3.2 NVIDIA 495.00". Did the AI hallucinate?

Well, it was telling us that there is an explicit GLES2 only path on Android, was it not? Do the presets work on the Shield with #36 version? If it is the case, then I would still say its better / cleaner solution.

**Comment by garbear** [comment]
The AI misread the EGL context request:

> `EGL_CONTEXT_CLIENT_VERSION = 2` does not necessarily mean the returned context is ES2; EGL can return a later backwards-compatible version, which explains the Shield reporting ES 3.2.

So my Shield ends up on ES 3.2, but other hardware can end up only ES 2. I don't have any ES 2 hardware to test with, so I'm not sure how the shaders work on that.

I'll test #36 on the Shield and see how the shaders work. It's functionally the same for #version 130 shaders. The remaining difference is whether the 110/120 shaders stay on the ESSL 1.00 path or get promoted to GLES 3 / ESSL 3.00.

**Comment by garbear** [comment]
I tried #36 on my Shield, and CRT Consumer fails.

AI use:

Tested the #36 approach on my Shield. It does make a functional difference even though the Shield is running GLES 3.2.

CRT Consumer fails to compile after promoting its GLSL 110 `convergence.glsl` pass to 150:

```text
error C7573: OpenGL/ES requires precision specifier on this float type
```

The promotion changes Kodi's effective shader from ESSL 100 to ESSL 300, which selects the modern shader path and exposes an `out vec4 FragColor` declaration before the fragment precision declaration.

With #38, that shader stays on its existing ESSL 100 path and works.

So I think this confirms we shouldn't promote the 110/120 shaders wholesale. The 130 -> 150 promotion is fine, but the older shaders need to retain their existing GLES path unless we separately port/test them for ESSL 300.

**Comment by KOPRajs** [comment]
> So I think this confirms we shouldn't promote the 110/120 shaders wholesale. The 130 -> 150 promotion is fine, but the older shaders need to retain their existing GLES path unless we separately port/test them for ESSL 300.

No, we shouldn't promote the versions without testing every individual shader for compatibility with the higher spec.

In this case I was expecting that this shader will work in ESSL 300, because you've reported it working in GLSL 1.50 (which is GL Core Profile 3.2) on the macOS.

If this holds true, then I would propose to remove the version string in this specific case, while keep `#version 150` for the others.

We then need to re-test this shader on the GL Core Profile, as it is going to be compile as `#version 460` (410 on macOS).

**Comment by garbear** [comment]
> No, we shouldn't promote the versions without testing every individual shader for compatibility with the higher spec.

By testing, do you mean running the shader manifest on both macOS and the Shield? For testing I do this, and can report no compiler errors and all shaders but some xbr ones look great.

> If this holds true, then I would propose to remove the version string in this specific case, while keep #version 150 for the others.

Do you mean how I've done it in this PR? Removing version strings while keeping #version 150 for the others? I've tested this on both Shield and macOS, no compiler errors and shaders look good.

**Comment by KOPRajs** [comment]
> Do you mean how I've done it in this PR? Removing version strings while keeping #version 150 for the others? I've tested this on both Shield and macOS, no compiler errors and shaders look good.

I would prefer `#version 150` over removed version, where we can. So only remove version for the presets, which don't work in GLES with `#version 150` (only _CRT Consumer_?).

**Comment by garbear** [comment]
OK, I'll switch all but CRT Consumer over to #version 150.

**Comment by garbear** [comment]
AI use:

I did another hardware test on the Shield, and the CRT Consumer exception needs to be broader than just `convergence.glsl`.

I left `convergence.glsl` versionless and promoted the other legacy shaders to `#version 150`. CRT Consumer then got past convergence but failed immediately on pass 1, `linearize.glsl`:

```text
CShaderGLES::Create: Failed to compile fragment shader:
.../crt-consumer/linearize.glsl

error C7573: OpenGL/ES requires precision specifier on this float type
(there is no default precision)
```

The problem is the same pattern we saw in `convergence.glsl`. `linearize.glsl` switches to the modern path when `__VERSION__ >= 130` and does this:

```glsl
#if __VERSION__ >= 130
#define COMPAT_VARYING in
#define COMPAT_TEXTURE texture
out vec4 FragColor;
#else
...
#endif

#ifdef GL_ES
...
precision highp float;
...
#endif
```

So after Kodi maps GLSL 150 to ESSL 300, `out vec4 FragColor` is declared before the fragment shader's default float precision. NVIDIA rejects that.

I checked the rest of CRT Consumer and `glow_x.glsl`, `glow_y.glsl`, and `crt-consumer.glsl` all have the same ordering. The preset is:

```text
convergence.glsl
linearize.glsl
glow_x.glsl
glow_y.glsl
crt-consumer.glsl
```

So promoting only some of those passes to 150 just moves the failure to the next CRT Consumer pass.

I think the right split is therefore:

* Keep all five CRT Consumer passes versionless, preserving their working ESSL 100/default path.
* Promote the other affected legacy GLSL shaders to 150 where hardware testing shows that path is valid.
* If we want CRT Consumer on ESSL 300 later, fix/port those shaders separately rather than changing their effective GLES version as part of the macOS compatibility fix.

This is on the Shield running OpenGL ES 3.2, so this isn't just a theoretical GLES2 compatibility concern—the promotion causes a real regression on GLES3 hardware too.

**Comment by KOPRajs** [comment]
Yes, either remove the version from all stages of the _CRT Consumer_ preset, or we can accept that this one simply won't work on macOS and don't modify it.
Set the version to 150 for all the others, which do work for both GL and GLES.

**Comment by garbear** [comment]
Done. Final testing on both platforms, then I'll merge.
